export const GET_EMPLOYEES = 'GET_EMPLOYEES';
export const SAVE_EMPLOYEE_LABEL = 'SAVE_EMPLOYEE_LABEL';
export const SAVE_BACKGROUND = 'SAVE_BACKGROUND';
export const ADD_EMPLOYEES = 'ADD_EMPLOYEES';
